app:
  name: personal-finance-management
  host: localhost
  port : 8386


database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: pfm-database
  ssl_mode: disable
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: 5m
  debug_level: info

jwt:
  access_secret: ${PFM_JWT_ACCESS_SECRET}
  refresh_secret: ${PFM_JWT_REFRESH_SECRET}
  access_token_expiry: 15m
  refresh_token_expiry: 168h  # 7 days
  reset_token_expiry: 1h
  verify_token_expiry: 24h
  issuer: personal-finance-management



cors:
  allow_origins:
    - "*"
  allow_methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allow_headers:
    - Origin
    - Content-Type
    - Accept
    - Authorization
    - X-Request-ID
  expose_headers:
    - X-Request-ID
  max_age: 86400


logger:
  level: debug
  format: console  # json or console
  output: stdout
  time_format: "2006-01-02T15:04:05.000Z07:00"

tracer:
  enabled: false
  service_name: cinemaos-backend
  endpoint: localhost:4317
  insecure: true
  sample_rate: 1.0